### ISSUE TITLE
Is the open source project abandoned?

### ISSUE THREAD

**Issue by ili101** [ironmansoftware/powershell-universal-legacy#57]
I can see on https://ironmansoftware.com/downloads/ that the last version is "PowerShell Universal 1.4.3" and it includes "Universal Dashboard 3.1.1" both are no longer marked as beta.

On here https://github.com/ironmansoftware/universal-dashboard and on the gallery https://www.powershellgallery.com/packages?q=UniversalDashboard the last versions are 3.0.0 beta X

1. Is the standalone version of Universal Dashboard that you can run without PowerShell Universal is abandoned (licensed and community)?
2. Is the open source Universal Dashboard Community project is abandoned?

**Comment by itfranck** [comment]
Hey @ili101 

Regarding the first point: 

Powershell universal / UD can still be run on IIS. See https://docs.ironmansoftware.com/config/hosting-iis

**Comment by adamdriscoll** [comment]
The open source project is no longer being maintained. Due to the complexity of maintaining both the open source fork and the closed source fork and the general lack of open source contributions, we decided to just merge UD into PSU and keep it closed source. We had been publishing the UD framework (PS1s + React components) on the Universal Dashboard repo as open source but have stopped that due to a lack of contributions. 

If there is a desire by the community for a continuation of publishing the frameworks as open source, I'm happy to set up some sort of automation to publish that to the public GitHub repo. 

PowerShell Universal contains all the features of Universal Dashboard and many more. It's free to use the same features that you would had in UD Community. We've realized that some people enjoyed the simplicity of UD being a PS module and that made it easier to deploy. We're trying to get PSU easier and easier to use so that it can be a viable replacement for someone's ad-hoc UD dashboard. 

If there are particular aspects of UD that you wish PSU had, I'm all ears.

**Comment by ili101** [comment]
Hi @adamdriscoll

This is my use case. I have a UniversalDashboard V2 tool, here is a simplified example:
MyTool\MyTool.ps1
``` powershell
Install-Module UniversalDashboard
Set-UDLicense -License 'xxx'
Get-UDDashboard | Stop-UDDashboard

$AuthenticationMethod = New-UDAuthenticationMethod -Endpoint {
    param([PSCredential]$Credentials)

    New-UDAuthenticationResult -Success -UserName "Adam"
    New-UDAuthenticationResult -ErrorMessage "You aren't Adam!!!"
}
$LoginPage = New-UDLoginPage -AuthenticationMethod $AuthenticationMethod -WelcomeText 'LOL'

$Page1 = New-UDPage -Name 'Services' -Icon link -Content {
    New-UDHeading -Text 'Page 1' -Size 4
}
$Page2 = New-UDPage -Name 'Process' -Icon home -Content {
    New-UDHeading -Text 'Get-Process' -Size 4
    New-UDInput -Title "User Data" -Endpoint {
        param($Name, [Bool]$Something)
        $Process = Get-Process -Name $Name
        New-UDInputAction -Toast "Found $($Process.Count) Processes"
        Set-UDElement -Id "results" -Content {
            New-UdGrid -Title "Processes" -Endpoint {
                $Process | Select-Object Name, ID, WorkingSet, CPU | Out-UDGridData
            }
        }
    }
    New-UDElement -Tag "div" -Id "results"
}

$Dashboard = New-UDDashboard -Title Test -Pages ($Page1, $Page2) -LoginPage $LoginPage
Start-UDDashboard -Dashboard $Dashboard -Port 5001 -AllowHttpForLogin
```
* I can get the last version from https://www.powershellgallery.com.
* Install my license.
* My tool code folder is located wherever I choose to put it with all the files inside.
* I have a simple authentication built in there in the ps1.
* I can just run it and I have my tool available on http://domain.

Now I want to update to V3
* I can't get the last version from the gallery as the last version is only on the website.
* The term 'Set-UDLicense' is not recognized as the name of a cmdlet.
* I have to put my tool in a fixed folder that is shared with my other tool.
* My 2 tools are sharing the same authentication and cannot be separated.
* I need to go to PSU to stop and start it and when it starts it's in a sub path of PSU instead of in it's own URL.

BTW I didn't know that V3 was release until yesterday and there are probably other users that don't realize this too as I was occasionally checking the gallery and keep seeing the 2 modules on version 3.0.0 beta X. The only way to know it's actually out of beta is to download Universal, open it and discover that you where waiting for no reason as 3.1.1 is out and it's out of beta for some time now.

**Comment by adamdriscoll** [comment]
Sounds good. Here's my plan. We will enhance the Universal PowerShell Module to allow for single file deployments like you are describing. Having transient instances of Universal is possible but requires some configuration which we can accomplish automatically with the enhancements to the module. It's possible right now but you would need to create various files and update other ones and that should be taken care of by the module itself. For example, the folders that you are describing that are shared by the two instances are configurable and you can change the dashboard path to the root but all of that requires knowledge that could be built in automatically.  Then, we'll make sure to publish the Universal Dashboard v3 and PowerShell Universal modules to the gallery as non-preview modules so that it's clear what's going on with UD.
